spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    #        database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: false
        show_sql: true
        format_sql: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=user
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false
    baseline-on-migrate: false
